; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:node]
platform = espressif32
board = esp32dev
framework = arduino
monitor_port = /dev/ttyUSB0
build_src_filter = +<node/>
upload_port = /dev/ttyUSB0
lib_deps = 
	jgromes/RadioLib@^7.6.0
	adafruit/Adafruit SSD1306@^2.5.16

[env:gateway]
platform = espressif32
board = esp32dev
framework = arduino
monitor_port = /dev/ttyUSB1
build_src_filter = +<gateway/>
upload_port = /dev/ttyUSB1
lib_deps = 
	jgromes/RadioLib@^7.6.0
